source ~/.config/nvim/init_subfiles/settings.vim
source ~/.config/nvim/init_subfiles/plugins.vim
source ~/.config/nvim/init_subfiles/keybinds.vim
source ~/.config/nvim/init_subfiles/tabline.vim
source ~/.config/nvim/init_subfiles/vimtex.vim
source ~/.config/nvim/init_subfiles/lsp.vim
source ~/.config/nvim/init_subfiles/autocommands.vim
source ~/.config/nvim/init_subfiles/functions.vim
source ~/.config/nvim/init_subfiles/colscheme.vim
